# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(0, 'None'), (1, 'Saturday 9:00 - 11:00'), (2, 'Saturday 11:30 - 13:30'), (3, 'Saturday 14:00 - 16:00'), (4, 'Saturday 16:30 - 18:30'), (5, 'Saturday 19:00 - 21:00'), (6, 'Sunday 9:00 - 11:00'), (7, 'Sunday 11:30 - 13:30'), (8, 'Sunday 14:00 - 16:00'), (9, 'Sunday 16:30 - 18:30'), (10, 'Sunday 19:00 - 21:00')])),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maths : numbers and place value', 'maths : numbers and place value'), ('maths : number sequences and properties', 'maths : number sequences and properties'), ('maths : addition and subtraction', 'maths : addition and subtraction'), ('maths : short and long multiplication', 'maths : short and long multiplication'), ('maths : times tables', 'maths : times tables'), ('maths : mode, median and mean', 'maths : mode, median and mean'), ('maths : fractions', 'maths : fractions'), ('maths : decimals', 'maths : decimals'), ('maths : coordinates', 'maths : coordinates'), ('maths : negative numbers', 'maths : negative numbers'), ('maths : multiplication involving decimals', 'maths : multiplication involving decimals'), ('maths : division', 'maths : division'), ('maths : calculations', 'maths : calculations'), ('maths : percentages', 'maths : percentages'), ('maths : rounding numbers', 'maths : rounding numbers'), ('maths : measurements', 'maths : measurements'), ('maths : solving problems', 'maths : solving problems'), ('maths : line graphs', 'maths : line graphs'), ('maths : algebra', 'maths : algebra'), ('maths : square, cube and triangular numbers', 'maths : square, cube and triangular numbers'), ('maths : factors, multiples and prime numbers', 'maths : factors, multiples and prime numbers'), ('maths : estimation', 'maths : estimation'), ('maths : ratio and proportion', 'maths : ratio and proportion'), ('maths : perimeter and area', 'maths : perimeter and area'), ('maths : angles', 'maths : angles'), ('maths : shapes', 'maths : shapes'), ('maths : volume', 'maths : volume'), ('maths : probability', 'maths : probability'), ('maths : statistics', 'maths : statistics')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], max_length=15)),
                ('out_of', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(height_field='height_field', upload_to='questions', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=-1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('classID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Class')),
            ],
        ),
        migrations.AddField(
            model_name='questiondone',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
