# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classID',
            field=models.IntegerField(default=-1),
        ),
    ]
