# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_classid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Algebra', 'Algebra'), ('Shapes', 'Shapes')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], max_length=15)),
                ('out_of', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(height_field=True, upload_to='questions', width_field=True)),
            ],
        ),
    ]
