# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.IntegerField(choices=[(4, 4), (5, 5)], default=5),
        ),
    ]
