# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to='questions', width_field='width_field'),
        ),
    ]
