# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[(6, 'Hard'), (5, 'Medium'), (4, 'Easy')], max_length=15),
        ),
    ]
