# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170919_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Place value', 'Place value'), ('Order and compare numbers', 'Order and compare numbers'), ('Negative numbers', 'Negative numbers'), ('Number sequences', 'Number sequences'), ('Estimation and Rounding', 'Estimation and Rounding'), ('Roman Numerals', 'Roman Numerals'), ('Solve problems on Number and Place Value', 'Solve problems on Number and Place Value'), ('Mental addition/subtraction', 'Mental addition/subtraction'), ('Addition/subtraction with decimals?', 'Addition/subtraction with decimals?'), ('Addition/Subtraction via column method', 'Addition/Subtraction via column method'), ('Estimation to check answers', 'Estimation to check answers'), ('Solve problems on addition and subtraction', 'Solve problems on addition and subtraction'), ('Timetables', 'Timetables'), ('Multiples', 'Multiples'), ('Mental/Basic multiplication', 'Mental/Basic multiplication'), ('Long multiplication', 'Long multiplication'), ('Long multiplication including decimals?', 'Long multiplication including decimals?'), ('Mental/Basic division', 'Mental/Basic division'), ('Short division', 'Short division'), ('Short division with decimals?', 'Short division with decimals?'), ('Testing divisibility', 'Testing divisibility'), ('Long division', 'Long division'), ('Long division with decimals', 'Long division with decimals'), ('Prime numbers', 'Prime numbers'), ('HCF and LCM', 'HCF and LCM'), ('Questions and Problems on factors and multiples', 'Questions and Problems on factors and multiples'), ('Square and cube numbers', 'Square and cube numbers'), ('Questions and Problems on square and cube numbers', 'Questions and Problems on square and cube numbers'), ('Mental mixed calculations', 'Mental mixed calculations'), ('BIDMAS', 'BIDMAS'), ('Questions and Problems on BIDMAS and mixed calculations', 'Questions and Problems on BIDMAS and mixed calculations'), ('Solve complex problems on all of the above (including real life)', 'Solve complex problems on all of the above (including real life)'), ('Basic fraction questions', 'Basic fraction questions'), ('Addition and Subtraction of fractions', 'Addition and Subtraction of fractions'), ('Multiplication and division of fractions', 'Multiplication and division of fractions'), ('Mixed and improper fractions', 'Mixed and improper fractions'), ('Mixture of fraction questions', 'Mixture of fraction questions'), ('Simplifying fractions', 'Simplifying fractions'), ('Equivalent fractions', 'Equivalent fractions'), ('Comparing and ordering fractions', 'Comparing and ordering fractions'), ('Unit and non-unit fractions', 'Unit and non-unit fractions'), ('Complex fraction questions', 'Complex fraction questions'), ('Solve fraction problems', 'Solve fraction problems'), ('Equivalent decimals to fractions', 'Equivalent decimals to fractions'), ('Decimal place value', 'Decimal place value'), ('Order decimal fractions', 'Order decimal fractions'), ('Percentage/decimal/fraction equivalents', 'Percentage/decimal/fraction equivalents'), ('Questions on percentages/decimals/fractions', 'Questions on percentages/decimals/fractions'), ('Solve problems on fractions/decimals/percentages', 'Solve problems on fractions/decimals/percentages'), ('Ratio and proportion', 'Ratio and proportion'), ('Solve problems on ratio and proportion', 'Solve problems on ratio and proportion'), ('Algebra', 'Algebra'), ('Solve problems on algebra', 'Solve problems on algebra'), ('Measure and compare', 'Measure and compare'), ('Add and subtract measurements', 'Add and subtract measurements'), ('Convert between units', 'Convert between units'), ('Convert between metric and imperial', 'Convert between metric and imperial'), ('Solve problems on measurement', 'Solve problems on measurement'), ('Solve problems on money', 'Solve problems on money'), ('What do I do for stuff that is exclusively year 4???', 'What do I do for stuff that is exclusively year 4???'), ('Analogue and digital clocks', 'Analogue and digital clocks'), ('12hour/24 hour', '12hour/24 hour'), ('Estimating times', 'Estimating times'), ('Time for calendars, timetables, roman numerals', 'Time for calendars, timetables, roman numerals'), ('Solve problems time)?', 'Solve problems time)?'), ('Perimeter', 'Perimeter'), ('Area', 'Area'), ('Area of parallelograms and triangles', 'Area of parallelograms and triangles'), ('Solve problems on area and perimeter', 'Solve problems on area and perimeter'), ('Volume', 'Volume'), ('Solve volume problems', 'Solve volume problems'), ('2D shapes', '2D shapes'), ('Compare and classify 2D shapes', 'Compare and classify 2D shapes'), ('Draw 2-D shapes', 'Draw 2-D shapes'), ('Questions on shapes', 'Questions on shapes'), ('Name parts of circle, radius, diameter, circumference', 'Name parts of circle, radius, diameter, circumference'), ('Solve problems on 2D shapes', 'Solve problems on 2D shapes'), ('3D shapes', '3D shapes'), ('Features of a 3D shape', 'Features of a 3D shape'), ('Solve problems on 3D shapes', 'Solve problems on 3D shapes'), ('Angles', 'Angles'), ('More Angles', 'More Angles'), ('Solve problems on angles', 'Solve problems on angles'), ('Symmetry in 2D shapes', 'Symmetry in 2D shapes'), ('Coordinates', 'Coordinates'), ('Drawing shapes on a coordinates graph', 'Drawing shapes on a coordinates graph'), ('Solve problems on coordinates', 'Solve problems on coordinates'), ('Bar Charts, Bar graphs, tally chart, pictograms and tables, time graphs', 'Bar Charts, Bar graphs, tally chart, pictograms and tables, time graphs'), ('Questions and interpreting all of the above', 'Questions and interpreting all of the above'), ('Solve problems on the above', 'Solve problems on the above'), ('Venn and Carroll diagrams', 'Venn and Carroll diagrams'), ('Pie charts and line graphs', 'Pie charts and line graphs'), ('Solve problems on the above', 'Solve problems on the above'), ('Mean, Median and Mode', 'Mean, Median and Mode'), ('Solve problems on mean, median and mode', 'Solve problems on mean, median and mode'), ('Solve problems on all of the above', 'Solve problems on all of the above')], max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('7', 'Very Difficult'), ('6', 'Year 6'), ('5', 'Year 5'), ('4', 'Year 4'), ('3', 'Year 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
