# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170925_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[(7, 'Very Difficult'), (6, 'Year 6'), (5, 'Year 5'), (4, 'Year 4'), (3, 'Year 3')], max_length=20),
        ),
    ]
